- name: variables
  hosts: local
  connection: local
  vars: #play level variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: print the variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
 - name: print the variables1
    vars: #task level vars
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
            