- name: variables
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the values
    private: false
  tasks:
  - name: print the variables
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "HELLO from {{ GREET }}"


      #preferences
      #1.command line or args 
      #2.task level
      #3.files
      #4.vars from prompt
      #5.play variables or global variables


