- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-096ce7f6200a4a729
    sg_id: sg-08777a9355c38caff
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
      - mysql
      - backend
      - frontend

  tasks:
    - name: install python libs
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: print ec2_info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"

    - name: print private IP addresses
      ansible.builtin.debug:
        mgs: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_info.results }}"