- name: nginx installation
  hosts: all
  become: yes
  serial: 1
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
